# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20 # just to bring forked repo uptodate
    ignore:
      - dependency-name: "kdbxweb" # for compatibility reasons
      - dependency-name: "@fortawesome/fontawesome-free"
      - dependency-name: "optimize-css-assets-webpack-plugin"
      - dependency-name: "eslint-plugin-promise"
      - dependency-name: "webpack-dev-server"
      - dependency-name: "marked"
#     eslint-config-prettier
#     grunt-webpack
#     prettier
#     webpack-bundle-analyzer
    target-branch: "develop"
